@startuml
main()
assert_argument_exists()
error()
usage()
print_version_info()
get_available_environments()
has()
get_dtc_installations()
sdk_home_doctoolchain()
is_supported_environment()
assert_environment_available()
is_environment_available()
is_doctoolchain_development_version()
get_environment()
is_doctoolchain_installed()
install_component_and_exit()
error_install_component_and_die()
local_install_doctoolchain()
assert_git_installed()
download_file()
assert_java_version_supported()
java_help_and_die()
how_to_install_sdkman()
local_install_java()
local_install_reveal_js()
assert_doctoolchain_installed()
how_to_install_doctoolchain()
assert_reveal_js_installed()
build_command()
show_os_related_info()

@enduml
