:filename: 030_news/2024/3.3-release.adoc
:jbake-title: Release v3.3
:jbake-date: 2024-02-18
:jbake-type: post
:jbake-tags: docToolchain
:jbake-status: published
:jbake-menu: news
:jbake-author: Ralf D. Müller
:icons: font

ifndef::imagesdir[:imagesdir: ../../../images]

== docToolchain release v3.3 (Bugfix-Release)


=== About This Release

This release fixes a problem with the docker image and dependencies in a restricted environment.
The docker image should already contain all required dependencies and thus should be able to run in an enviroment without internet connection (build pipeline).
With the latest im provements, a change was introduced which broke this feature.
This resulted in timeouts for the dependency resolution.

We now managed to fix this again.

We also introduced an enviroment variable DTC_DOCKER_PREFIX to specify an internal docker hub for the docker image.
This should also help to run docToolchain in restricted environments.

Other changes fix problems with custom ruby extensiosn for PDF generation and features for `publishToConfluence`

IMPORTANT: this release breaks the `generateDeck` task.

== Notes

=== fixes

* [Noticket] Enforce x86 Java on macOS as long as jbake does not support arm64 processors
* [Noticket] Avoid usage of an arbitrary `arch` binary/script on `+${PATH}+` instead of the desired `/usr/bin/arch` on macOS.
* https://github.com/docToolchain/docToolchain/issues/1353[#1353: docker: Problem with 3.x images and dependencies?]
* https://github.com/docToolchain/docToolchain/issues/1239[#1239: Execute a custom asciidoctor converter for generateHTML]
* https://github.com/docToolchain/docToolchain/issues/1290[#1290: Custom ruby extension for PDF generation]
* https://github.com/docToolchain/docToolchain/issues/1355[#1355: publishToConfluence - some code blocks are generated as txt instead of requested language and loose linebreaks]
* https://github.com/docToolchain/docToolchain/issues/1349[#1349: publishToConfluence - a source code block containing template parameters has formatting problems]

=== changed

* you can now specify another dockerhub via DTC_DOCKER_PREFIX


[TIP]
====
You like docToolchain? +
What about helping to make it even better? +
docToolchain is a community project, so be part of the community which drives the project. +
You don't have to code for doing so. +
It would even help to brush up the docs, write tutorials or groom the backlog +
(I guess many of the open issues are already fixed).
====
