= How to install docToolchain

== Default configuration

Let's get started...

Assuming that you first create your solution architecture and then the code, you simply start by getting a copy of the current docToolchain repository.
The easiest way is to clone the repository without history and remove the `.git` folder:

.Linux with git clone
[source,bash]
----
git clone --recursive https://github.com/docToolchain/docToolchain.git <your project name>
rm -rf .git
rm -rf resources/asciidoctor-reveal.js/.git
rm -rf resources/reveal.js/.git
----

`--recursive` option is required because the repository contains 2 submodules - `resources/asciidoctor-reveal.js` and `resources/reveal.js`.

Another way is to download the zipped git repository and rename it:

.Linux with download as zip
[source, bash]
----
wget https://github.com/docToolchain/docToolchain/archive/master.zip
unzip master.zip

# fetching dependencies

cd docToolchain-master/resources

rm -d reveal.js
wget https://github.com/hakimel/reveal.js/archive/tags/3.3.0.zip -O reveal.js.zip
unzip reveal.js.zip
mv reveal.js-tags-3.3.0 reveal.js

rm -d asciidoctor-reveal.js
wget https://github.com/asciidoctor/asciidoctor-reveal.js/archive/9667f5c.zip -O asciidoctor-reveal.js.zip
unzip asciidoctor-reveal.js.zip
mv asciidoctor-reveal.js-9667f5c5d926b3be48361d6d6413d3896954894c asciidoctor-reveal.js

mv docToolchain-master <your project name>
----


If you work (like me) on a Windows environment, just download and unzip the https://github.com/docToolchain/docToolchain/archive/master.zip[repository] as well as its dependencies:
https://github.com/hakimel/reveal.js/archive/tags/3.3.0.zip[reveal.js] and
https://github.com/asciidoctor/asciidoctor-reveal.js/archive/9667f5c.zip[asciidoctor-reveal.js].

After unzipping, put the dependencies in `resources` folder, so that the structure is the same as on https://github.com/docToolchain/docToolchain/tree/master/resources[GitHub].

//[source]
//----
//(New-Object Net.WebClient).DownloadFile('https://github.com/docToolchain/docToolchain/archive/master.zip','master.zip')
//----

This should already be enough to start a first build:


.linux with gradle wrapper
[source, bash]
----
./gradlew
----

.linux with maven wrapper
[source, bash]
----
./mvnw
----

.Windows with gradle wrapper
[source, bash]
----
./gradlew
----

.Windows with maven wrapper
[source, bash]
----
./mvnw.bat
----

As a result, you will see the progress of your build together with some warnings which you can just ignore for the moment.

The first build generated some file within the `<project>/build` folder:

[source]
----
<project>:
    build:
        docs:
            html5:
                images:
                arc42-template-de.html
                arc42-template-end.html
            pdf:
                arc42-template-de.pdf
----

*Congratulations!* if you see the same folder structure, you just managed to render the standard arc42 template as html and pdf!

If you didn't get the right output, please raise an issue on https://github.com/docToolchain/docToolchain/issues[github]

== Custom configuration

You can install docToolchain in a directory separate from your project. Then docToolchain is a standalone tool that can be
upgraded independently from your code or used for multiple projects.
If you want to install docToolchain separately, you need to create a copy of Config.groovy and
ConfluenceConfig.groovy for each project. Inside each configuration file you need to specify the input and output
folders and files.

The paths to those configuration files can be provided by giving -P option to gradlew, for example:

[source, bash]
----
./gradlew -PconfluenceConfigFile=$HOME/projectA/ConfluenceConfig.groovy -PmainConfigFile=$HOME/projectA/Config.groovy
./gradlew -PconfluenceConfigFile=$HOME/projectB/ConfluenceConfig.groovy -PmainConfigFile=$HOME/projectB/Config.groovy
----
