= How to install docToolchain

== Default configuration

Let's get started...

Assuming that you first create your solution architecture and then the code, you simply start by getting a copy of the current docToolchain repository.
The easiest way is to clone the repository without history and remove the `.git` folder:

.linux with git clone
[source,bash]
----
git clone https://github.com/rdmueller/docToolchain.git <your project name>
rm -rdI .git
----

Another way is to download the zipped git repository and rename it:

.linux with download as zip
[source, bash]
----
wget https://github.com/rdmueller/docToolchain/archive/master.zip
unzip master.zip
mv docToolchain-master <your project name>
----


If you work (like me) on a windows environment, just download and unzip the https://github.com/rdmueller/docToolchain/archive/master.zip[repository].

//[source]
//----
//(New-Object Net.WebClient).DownloadFile('https://github.com/rdmueller/docToolchain/archive/master.zip','master.zip')
//----

This should already be enough to start a first build:


.linux with gradle wrapper
[source, bash]
----
./gradlew
----

.linux with maven wrapper
[source, bash]
----
./mvnw
----

.windows with gradle wrapper
[source, bash]
----
./gradlew
----

.windows with maven wrapper
[source, bash]
----
./mvnw.bat
----

As a result, you will see the progress of your build together with some warnings which you can just ignore for the moment.

The first build generated some file within the `<project>/build` folder:

[source]
----
<project>:
    build:
        docs:
            html5:
                images:
                arc42-template-de.html
                arc42-template-end.html
            pdf:
                arc42-template-de.pdf
----

*Congratulations!* if you see the same folder structure, you just managed to render the standard arc42 template as html and pdf!

If you didn't get the right output, please raise an issue on https://github.com/rdmueller/docToolchain/issues[github]

== Custom configuration

If you want to use the same docToolchain for multiple projects, you need to create a copy of Config.gradle and ConfluenceConfig.gradle for each project.
The paths to those configuration files can be provided by giving -P option to gradlew, for example:

[source, bash]
----
./gradlew -PconfluenceConfigFile=$HOME/projectA/ConfluenceConfig.gradle -PmainConfigFile=$HOME/projectA/Config.gradle
./gradlew -PconfluenceConfigFile=$HOME/projectB/ConfluenceConfig.gradle -PmainConfigFile=$HOME/projectB/Config.gradle
----

Then inside each configuration file you need to specify input and output folders and files.
