:filename: manual/03_task_exportContributors.adoc

= exportContributors

include::feedback.adoc[]

This tasks crawls through all Asciidoctor source files and extracts a list of contributors.
This list is then rendered as AsciiDoc images of the contributor's gravatar picture.

The extracted lists are stored in `{targetDir}/contributors/{filename}` to be easily included in your documents.

Best way to use this feature is to create a `feedback.adoc` file which might look like this:

.feedback.adoc
[source,asciidoc,indent=0]
// the contents of the following source block are indented to prevent the ifndef/endif/include to resolve
----
    ifndef::backend-pdf[] // <1>

        image::https://img.shields.io/badge/improve-this%20doc-orange.svg[link={manualdir}{filename}, float=right] // <2>
        image::https://img.shields.io/badge/create-an%20issue-blue.svg[link="https://github.com/docToolchain/documentation/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23page:{filename}", float=right] // <3>

    endif::[]

    include::{targetDir}/contributors/{filename}[] // <4>
----

<1> do not show this section when rendered as PDF
<2> create an "improve this doc" button which links to the git sources
<3> create a "create-an-issue" button which links to your issue tracker
<4> include the list of contributors created by this task

== Reading Time

The task also appends to the list of contributors the estimated reading time.

== File Attributes

The task now also exports some attributes of the git files.
The extracted attributes are stored in `{targetDir}/fileattribs/{filename}`.

[source,asciidoc]
----
:lastUpdated: 16.05.2019 06:22
:lastAuthorName: Ralf D. Müller
:lastAuthorEmail: ralf.d.mueller@gmail.com
:lastAuthorAvatar: http://www.gravatar.com/avatar/cc5f3bf8b3cb91c985ed4fd046aa451d?d=identicon[32,32,role='gravatar',alt='Ralf D. Müller',title='Ralf D. Müller']
:lastMessage: #310 started to document config options
----

This enables you to import these attributes the same way you import the contributors list and use these attributes.

Here is an example:

.feedback.adoc
[source,asciidoc,indent=0]
// the contents of the following source block are indented to prevent the ifndef/endif/include to resolve
----
    include::{targetDir}/fileattribs/{filename}[]

    Last updated {lastUpdated} by {lastAuthorName}
----
