ifndef::imagesdir[:imagesdir: ../images]

= FAQ: Frequently asked Questions

This section tries to answer the most common and frequently asked questions about how to work with docToolchain.
It will also contain questions relevant to the tools used to build docToolchain, but the main focus is docToolchain itself.

If you are stuck, make sure that you also check other sources like https://stackoverflow.com/questions/tagged/asciidoctor[stackoverflow].

There is also a great FAQ for all your arc42 questions: http://faq.arc42.org/home/

If you have a question or problem for which you can't find a solution, you can

* for this repo, add your question and create a pull request
* raise the issue through the https://github.com/docToolchain/docToolchain/issues[github issue tracker]
* ask your question on https://stackoverflow.com/questions/tagged/doctoolchain?sort=active&pageSize=50[stackoverflow]
* discuss the problem on https://t.co/lnqrUc1YMM[slack]

== Images

* http://asciidoctor.org/docs/user-manual/#images[Asciidoctor User Manual on images]
* http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#images[Asciidoctor Quick Reference on images]
* http://asciidoctor.org/docs/asciidoc-writers-guide/#images[Asciidoctor Writer Guide on images]

=== Q: Why are images not shown in the preview of my editor?

A: this is most likely because your editor doesn't know where they are stored.
If you follow the default settings, you probably store your images in a subfolder `images`.
The build script knows about it, because the attribute `imagesdir` has been set to `./images`, but your editor doesn't care about the build script - it only checks the currently opened AsciiDoc file.

The solution is to add a line to each file which checks if the `imagesdir` is set and if not, sets it to a valid value:

`ifndef::imagesdir[:imagesdir: ../images]`

=== Q: Which image format should I use?

A: AsciiDoc and asciidoctor support several formats like GIF, PNG, JPG and SVG.
However, if you want to use most features, some formats are better to use than others:

GIF:: is not supported by the PDF renderer. Use JPG or PNG instead.

JPG:: is great for photos but not for digrams (you might get compression artefacts).
So, if you want to use photos from your flipcharts - JPG might work for you.

SVG:: great for high resolution diagrams, but not good supported by DOCX as output format.
OpenOffice Writer might display the image a bit stretched, MS Word didn't display it at all in some experiments.

PNG:: this is the preferred format for images used with docToolchain.
All output formats support it and if diagrams are rendered with a resolution high enough to display all details, it will also be scaled ok with all output formats.

=== Q: Why are my images rotated in the output?

A: This most likely happens when you've taken photos with a mobile device and include them in you docs.
A mobile device does not rotate the image itself, it only stores the orientation of the device in the meta data of the photo.
Your operating system will show you the image as expected, but the rendered AsciiDoc will not.
This can be „fixed“ with Imagemagick, use convert -auto-orient or mogrify -auto-orient (thanx to https://twitter.com/RalfDMueller/status/920888868345384960[@rotnroll666] for this tip).
YOu can also try to just open the image in your favourite editor and re-save it.

== PlantUML

TODO
