:jbake-order: 10
:filename: 020_tutorial/010_Install.adoc
:jbake-title: Install docToolchain
include::_config.adoc[]

== Welcome!

Nice to meet you.
Glad that you want to learn more about using docToolchain.
Start by installing what you need.

The following steps are the same as described in the User Docs.
Please follow them step by step.
You are prompted to install everything you need for each step.

If you encounter problems, create a GitHub issue and the community will help you.

include::../010_manual/20_install.adoc[tags=install]

=== Problems & solutions

==== `dtcw` doesn't run

You might get an error similiar to this one:

[source]
----
./dtcw local tasks --group=doctoolchain
./dtcw: line 1: syntax error near unexpected token `newline'
./dtcw: line 1: `<!DOCTYPE html>'
----

If you see that, it's likely that the wrapper didn't download correctly.
You can that an HTML page was downloaded instead of the wrapper.
Please try to redownload the wrapper.

==== Incompatible Java version

You may see that docToolchain starts but crashes with a stacktrace that starts like this:

[source]
----
* What went wrong:
Could not compile settings file '/Users/falk/.doctoolchain/docToolchain-2.0.0/settings.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 61
  
  java.lang.IllegalArgumentException: Unsupported class file major version 61
----  

In this case, you've got an incompatible version of Java.
`dtcw` tries to check the Java version up front by running  `java --version`, but Gradle sometimes picks up a different version.
If you get a similar error, try reinstalling a compatible Java version.
