:filename: 030_news/2021/2.0.0-release.adoc
:jbake-title: Release v2.0.0
:jbake-date: 2021-09-23
:jbake-type: post
:jbake-tags: docToolchain
:jbake-status: draft
:jbake-menu: news
:jbake-author: Ralf D. Müller

ifndef::imagesdir[:imagesdir: ../../../images]

== v2.0.0 of docToolchain has been released!

Today docToolchain reached an important milestone - the release of version 2.0.0 aka ng or next-generation.

The focus of this huge release is simplified setup, better usability and distraction free writing.

=== Which new features can you expect?

The most important change is the *switch to a command-line based approach*.
You can now fully focus on your documentation without having lots of other files like scripts or themes in your repository.

This is possible through the introduction of the *docToolchain-wrapper* or short dtcw.
A little script that resides together with a config file in your repository.
It takes care to use the right version of docToolchain, all pre-requisites are met, and it even checks if it should use docker or a local installation to execute docToolchain.
If docToolchain is not installed, it will install it for you.

Another change is that we tried very hard to *avoid error messages*.
Where we can't avoid errors, we tried to convert them to helpful hints.
This should make the use of docToolchain a better experience.

Another huge added feature is the link:../015_tasks/03_task_generateSite.html[`generateSite`]-Task which includes jBake as *static site generator* to help you even more to create awesome docs.
You can now create a full documentation website with less than a handful commands.
It uses the beautiful docsy theme known from hugo, and it even contains a link:../search.html[*local search*] implemented with lunr.

To get you started with your solution architecture documentation, we've added the `downloadTemplate`-task to provide you with the famous *arc42 template* in four languages.

Last but not least, we used the new `generateSite`-Feature to restructure the documentation of docToolchain itself.

The goal for the next weeks is now to provide you with tutorials over the next few weeks to demonstrate all new features.

IMPORTANT: Thanx to all contributors, sponsors, and users of docToolchain for your efforts!
Without you, this project would not exist 💯

Happy writing!

Ralf

[.small]#PS: thanx to http://ahus1.de/[Alexander Schwartz]g for proofreading this announcement#

ad-sm

=== Changelog for v2.0.0

==== added
2021-09-21::
* added lunrjs as local search engine
2021-09-06::
* added warning when running on WSL
* added dtcw.bat to avoid execution restrictions
* updated developer docs
* added docsy as theme
2021-05-21::
* if the outputPath from the config starts with a '/', it will be considered as absolute path. +
This way, you can move the build fodler outside of your repository. +
`outputPath = System.getenv('HOME')+'/.doctoolchain/build/'+(new File('.')).canonicalPath.md5()`
* repository theme gets only copied to build if it is defined in `siteFolder`
* generateSite will now add meta-data to all asciidoc files which have no meta-data defined. The menu name and order will be created corresponding to the folder and file name. The title will be extracted as first headline from the file itself.
2021-05-18::
* Headless mode for themes
* fix landing page (only gets copied once when microsite config isn't set yet.)

2021-04-07::
* generateSite can now handle themes
2021-04-09::
* downloadTemplate can now handle further templates

2021-02-26::
* copyThemes task
* generateSite task
2021-02-23::
* first version of powershell wrapper
2021-02-22::
* manual test script
2021-01-05::
* dtc wrapper
2021-01-08::
* first definition of a static site taken from arc42-template-project
* updated gradle wrapper (6.6.1)
* added downloadTemplates task
* added feature to automatically create a Config file if it doesn't exist
* configured gradle to run without daemon

==== changed

2021-09-22::
* streamingExecute (exportPPT, exportEA) now emits a note instead ot an error when running on linux
* brushed up powershell wrapper


==== fixed

2021-09-21::
* updated exportContributors to follow moved files
* fixed downloadTemplate

2021-09-18::
* fixed favicons
* fixed blog
2021-05-22::
* fix copyThemes to also copy the external theme
2021-05-06::
* fix #574: publishToConfluence: Problem with wrong ancestorId
2021-04-28::
* fix copyImages for generateSite

2021-03-02::
* removed default imagesdir for generateSite

2021-03-01::
* fixed imagesdir typo

2021-03-01::
* updated docs for generateSite
* fixed menu for generateSite

2021-02-27::
* fixed createDist task
* fixed plantUML for generatePDF
* fixed plantUML for generateSite

2021-02-24::
* [543] dtcw: added pre-requisites check and alternative curl instead of wget
2021-02-22::
* handling of images for generateHTML


