:filename: 030_news/2023/3.0.2-release.adoc
:jbake-title: Release v3.0.2
:jbake-date: 2023-09-11
:jbake-type: post
:jbake-tags: docToolchain
:jbake-status: published
:jbake-menu: news
:jbake-author: Ralf D. Müller
:icons: font

ifndef::imagesdir[:imagesdir: ../../../images]

== docToolchain release v3.0.2 (Bugfix-Release)

We just had to create Bugfix-Release v3.0.2 

=== About This Release

The v3.0.1 Release created a non-working default config. This release fixes this blocker.

== Notes


== 3.0.2 - 2023-09-12

=== fixes


* https://github.com/docToolchain/docToolchain/pull/1246[#1246: publishToConfluence: Fix comparision error for titles with leading/trailing white spaces]
* https://github.com/docToolchain/docToolchain/issues/1248[#1248: broken default config]

=== changed


=== Discussion

To discuss the new features, a new https://github.com/docToolchain/docToolchain/discussions/1250[discussion thread] has been created.

NOTE: a big "THANK YOU" to all *Sponsors* and *Contributors* who helped to support docToolchain!

[TIP]
====
You like docToolchain? +
What about helping to make it even better? + 
docToolchain is a community project, so be part of the community which drives the project. +
You don't have to code for doing so. +
It would even help to brush up the docs, write tutorials or groom the backlog +
(I guess many of the open issues are already fixed).
====
