:filename: 030_news/2023/3.1.0-release.adoc
:jbake-title: Release v3.1.0
:jbake-date: 2023-11-03
:jbake-type: post
:jbake-tags: docToolchain
:jbake-status: published
:jbake-menu: news
:jbake-author: Pascal Euhus
:icons: font

ifndef::imagesdir[:imagesdir: ../../../images]

== docToolchain release v3.1.0!

=== About This Release

Here it is: docToolchain v3.1.0!
It contains two major changes:
* docToolchain starts to become more modularized. This enables us to provide a core component which can be used by other projects as well, *without* the use of Gradle. Though, Gradle will still get the full support.
* Atlassian is currently deprecating the Confluence API v1. This release candidate contains the first steps to support the new API v2. From January 2024 on,
the old API will be shut down for all *Cloud Instances* (https://community.developer.atlassian.com/t/deprecating-many-confluence-v1-apis-that-have-v2-equivalents/66883[see]).
While the script logic was mostly unaffected, the RestClient had to be rewritten.
Although we tested everything, we need your help to test the new API to verify we didn't miss anything.

== Notes

* to switch to the new API, you have to set the `confluence.useV1Api` property to `false` in your `docToolchainConfig.groovy` file.
This is recommended for all users using Confluence Cloud.

== 3.1.0 - 2023-11-03

=== fixes

* https://github.com/docToolchain/docToolchain/pull/1262[#1262: downloadTemplate skips creating a folder, causes generateSite to fail]
* https://github.com/docToolchain/docToolchain/issues/1269[#1269 Fix wrong bash usage on Darwin with Homebrew]
* https://github.com/docToolchain/docToolchain/issues/1270[#1269 Ensure DTC_JAVA_HOME is preferred over JAVA_HOME]
* https://github.com/docToolchain/docToolchain/issues/1069[#1069 publishToConfluence 'ancestorName' query does not support proxy]
* https://github.com/docToolchain/docToolchain/issues/1272[#1272: publishToConfluence broken when document contains internal links]

=== added

* https://github.com/docToolchain/docToolchain/issues/1254[configure Confluence API parameters via Gradle parameters]
* introduce `verifyConfluenceApiAccess` task - check if your API settings are correct

=== changed

* introduce docToolchain core component to modularize the project
* implement Confluence API v2 support

[TIP]
====
You like docToolchain? +
What about helping to make it even better? +
docToolchain is a community project, so be part of the community which drives the project. +
You don't have to code for doing so. +
It would even help to brush up the docs, write tutorials or groom the backlog +
(I guess many of the open issues are already fixed).
====
