:filename: 030_news/2023/3.1.1-release.adoc
:jbake-title: Release v3.1.1
:jbake-date: 2023-11-07
:jbake-type: post
:jbake-tags: docToolchain
:jbake-status: published
:jbake-menu: news
:jbake-author: Pascal Euhus
:icons: font

ifndef::imagesdir[:imagesdir: ../../../images]

== docToolchain release v3.1.1 (Bugfix-Release)

We just had to create Bugfix-Release v3.1.1

=== About This Release

The v3.1.0 Release could not handle Confluence attachments. This release fixes this blocker.

IMPORTANT: please also check the xref:3.1.0-release.adoc[release notes for v3.1.0]

== Notes

== 3.1.1 - 2023-11-07

=== fixes

* https://github.com/docToolchain/docToolchain/issues/1281[#1281: publishToConfluence throws exception when uploading attachments in v3.1.0]
* https://github.com/docToolchain/docToolchain/issues/1283[#1283: "tasks" target causes Exception]


=== changed

* Improve docs for `publishToConfluence` task

NOTE: a big "THANK YOU" to all *Sponsors* and *Contributors* who helped to support docToolchain!

[TIP]
====
You like docToolchain? +
What about helping to make it even better? +
docToolchain is a community project, so be part of the community which drives the project. +
You don't have to code for doing so. +
It would even help to brush up the docs, write tutorials or groom the backlog +
(I guess many of the open issues are already fixed).
====
