:filename: 030_news/2023/2.2.1-release.adoc
:jbake-title: Release v2.2.1
:jbake-date: 2023-03-05
:jbake-type: post
:jbake-tags: docToolchain
:jbake-status: published
:jbake-menu: -
:jbake-author: Ralf D. Müller
:icons: font

ifndef::imagesdir[:imagesdir: ../../../images]

== docToolchain v2.2.1 has Been Released!

=== About This Release

Great News! docToolchain now comes with http://structurizr.com/[structurizr], a library which let's you model your diagrams-as-code views and we have better automated tests for the doctoolchain wrapper `dtc`!

To discuss the new features, a new https://github.com/docToolchain/docToolchain/discussions/1072[discussion thread] has been created.

NOTE: a big "THANK YOU" to all *Sponsors* and *Contributors* who helped to support docToolchain!

[TIP]
====
You like docToolchain? 
What about helping to make it even better? 
docToolchain is a community project, so be part of the community which drives the project. 
You don't have to code for doing so. 
It would even help to brush up the docs, write tutorials or groom the backlog 
(I guess many of the open issues are already fixed).
====

== 2.2.1 - 2023-03-05

=== fixes

* use the configured proxy when publishing labels to confluence pages
* https://github.com/docToolchain/docToolchain/issues/1054[#1054] : fix for `publishToConfluence` was broken in v2.2.0
* https://github.com/docToolchain/docToolchain/issues/1063[#1063] : fix for `exportConfluence` broken path for partial exports

=== added

* http://doctoolchain.org/docToolchain/v2.0.x/015_tasks/03_task_exportStructurizr.html[exportStructurizr Task]
* https://github.com/docToolchain/docToolchain/tree/ng/test[automated tests for dtcw]

=== changed

* automate the use of x86 emulator on apple silicon in dtcw
* updated jBake Markdown extensions and added FENCED_CODE_BLOCKS

