:filename: 015_tasks/03_task_exportJiraIssues.adoc
include::_config.adoc[]

== exportJiraIssues

include::../_feedback.adoc[]

=== About This Task

This task exports all issues for a given query or queries from Jira as either an AsciiDoc table or an Excel file.

The configuration for this task can be found within `Config.gradle` (`gradle.properties` can be used as a fallback).
Username/password is deprecated, so you need to use username/API-token instead.

An API-token can be created through https://id.atlassian.com/manage/api-tokens[].
We recommend that you keep username and API-token out of your GitHub repository, and instead pass them as environment variables to docToolchain.

=== Configuration

Jira configuration support list requests to Jira where results of each requests will be saved in a file with specifies filename. Flags
_saveAsciidoc_ & _saveExcel_ allow you to easily configure the format in which results should be saved.

IMPORTANT: The old configuration was based on the *single Jira query is deprecated* (single 'jql' parameter). Support for it will be removed in the near future. Please migrate to the new configuration which allows multiple Jira queries.

.Config.groovy
[source,groovy]
----
include::{projectRootDir}/Config.groovy[tags=jiraConfig]
----

=== Further Reading and Resources

Read the https://rdmueller.github.io/Jira/[Living Documents for Agile Projects] blog post.

=== Source

:param_source_file: scripts/exportJiraIssues.gradle
:param_source_language: groovy
:param_source_tags: exportJiraIssues
include::_viewTaskSource.adoc[]
