:filename: 015_tasks/03_task_exportJiraSprintChangelog.adoc
include::_config.adoc[]

= exportJiraSprintChangelogIssues

include::../_feedback.adoc[]

== About This Task

This task exports a simplified (key and summary) list of Jira issues for a specific sprint defined in the task configuration. Only a few additional fields (such as assignee) can be switched using configuration flags.

Once you define the sprint, the relevant AsciiDoc and Excel files will be generated.
If a sprint is not defined in the configuration, changelogs for all sprints that match the configuration will be saved in separate AsciiDoc files and in different tabs within an Excel file.

The task configuration can be found within `Config.gradle`. In addition to the configuration snippet below, it is important to configure the Jira API and credentials in the Jira section of the configuration inside the same file.

== Configuration

.Config.groovy
[source,groovy]
----
include::{projectRootDir}/Config.groovy[tags=sprintChangelogConfig]
----

== Source

.exportJiraSprintChangelog.gradle
[source,groovy]
----
include::{projectRootDir}/scripts/exportJiraSprintChangelog.gradle[tags=exportJiraSprintChangelog]
----
