:filename: 015_tasks/03_task_exportDrawIo.adoc
include::_config.adoc[]
:experimental:

= exportDrawIo

include::../_feedback.adoc[]

== About This Task
There is no `exportDrawIo` task available in docToolchain because such a task is not required.
You can continue to use https://app.diagrams.net/[diagrams.net] (formerly known as draw.io) to edit your diagrams simply by making a change to your diagram-authoring workflow.

== About diagrams.net

diagrams.net offers free and open source desktop editors for all major operating system platforms.
Visit https://www.diagrams.net/integrations to find a desktop editor application compatible with your operating system.
When you use the desktop version, just create your diagram with the `.png` (or even better, `.dio.png`) extension and diagrams.net will always save your diagram as a PNG with the source as metadata.

They have also launched a free plugin for VS Code and IntelliJ so you can edit your diagrams offline!

== How to Change Your Workflow to Use diagrams.net

Export your diagrams.net/draw.io diagrams as a PNG with the source embedded in the file metadata.
This allows you to embed your diagrams into AsciiDoc source as you normally would (using the `image::` macro) with the added advantage of storing the diagram source with the image itself.

== How to Convert a Confluence Page to AsciiDoc

If you are converting a Confluence page with embedded draw.io diagrams to AsciiDoc, use this export workflow to continue using diagrams.net:

. Export an editable PNG diagram from Confluence.
. Load the diagram you want to export from Confluence.
. Click menu:File[Export as > PNG...].
. In the Image modal, make sure that **Include a copy of my diagram** is selected.
. Click **Export** to save the PNG file with the pattern `[file].dio.png`.
. Commit the exported PNG file to source control.

Your diagram can now be managed in source control, added to your documentation source and edited using a diagrams.net desktop version.

NOTE: Specifying `.dio` (short for "**d**raw**io**") in the name will help you identify PNG files containing an embedded XML diagram source.


++++
<script src="https://plugins.jetbrains.com/assets/scripts/mp-widget.js"></script>
<script>
  // Please, replace #yourelement with a real element id on your webpage
  MarketplaceWidget.setupMarketplaceWidget('card', 15635, "#myelement");
</script>
<div id="myelement"></div>
++++
