:filename: 015_tasks/03_task_exportContributors.adoc
include::_config.adoc[]

== exportContributors

include::../_feedback.adoc[]

=== About This Task

This task crawls through all Asciidoctor source files and extracts a list of contributors, which is then rendered as AsciiDoc images of each contributor's gravatar picture.
The extracted list is stored in `{targetDir}/contributors/{filename}` so it can be easily included in your documents.

=== How to Use This Task

The best way to use this task is to create a `feedback.adoc` file similar to this:

.feedback.adoc
[source,asciidoc,indent=0]
// the contents of the following source block are indented to prevent the ifndef/endif/include to resolve
----
    ifndef::backend-pdf[] // <1>

        image::https://img.shields.io/badge/improve-this%20doc-orange.svg[link={manualdir}{filename}, float=right] // <2>
        image::https://img.shields.io/badge/create-an%20issue-blue.svg[link="https://github.com/docToolchain/documentation/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23page:{filename}", float=right] // <3>

    endif::[]

    include::{targetDir}/contributors/{filename}[] // <4>
----
.Key:
<1> Do not show this section when docs are rendered as PDF.
<2> Create an **Improve This Doc** button which links to your GitHub sources.
<3> Create a **Create an Issue** button which links to your issue tracker.
<4> Include the list of contributors created by this task.

_(The task automatically adds the estimated reading time to the list of contributors.)_

=== About the Avatar-Icons

It seems not to be possible to extract a link to the github avatar icons from the log.
So, the solution is to use https://gravatar.com[Gravatar] icons.
For this to work, the contributors email address is hashed and an icon link is generated from that hash.

    http://www.gravatar.com/avatar/cc5f3bf8b3cb91c985ed4fd046aa451d?d=identicon

This result at least in an icon which has a distinct color.

Contributors can set up their own image through https://gravatar.com[Gravatar.com].
For this to work, the git commits need to use an email address which can be verified by Gravatar.com.
Unfortunately, this is not the case if a contributor decided to make his email address private in the email sections of her github account.

=== File Attributes

This task also exports some GitHub file attributes.
The extracted attributes are stored in `{targetDir}/fileattribs/{filename}`.

[source,asciidoc]
----
:lastUpdated: 16.05.2019 06:22
:lastAuthorName: Ralf D. Müller
:lastAuthorEmail: ralf.d.mueller@gmail.com
:lastAuthorAvatar: http://www.gravatar.com/avatar/cc5f3bf8b3cb91c985ed4fd046aa451d?d=identicon[32,32,role='gravatar',alt='Ralf D. Müller',title='Ralf D. Müller']
:lastMessage: #310 started to document config options
----

You can import and use these attributes in the same way as you import the contributors list.

IMPORTANT: please make sure that you do not accidentally publish the email address if your contributors do not want it.

For example:

.feedback.adoc
[source,asciidoc,indent=0]
// the contents of the following source block are indented to prevent the ifndef/endif/include to resolve
----
    include::{targetDir}/fileattribs/{filename}[]

    Last updated {lastUpdated} by {lastAuthorName}
----
