:filename: 015_tasks/03_task_generatePDF.adoc
include::_config.adoc[]

= generatePDF

include::../_feedback.adoc[]

== At a Glance

== About This Task

This task makes use of the https://asciidoctor.org/docs/convert-asciidoc-to-pdf/[asciidoctor-pdf] plugin to render your documents as pretty PDF files.
Files are written to `build/pdf`.
The PDF is generated directly from your AsciiDoc sources. There is no need for an intermediate format or other tools.
The result looks more like a nicely rendered book than a print-to-PDF HTML page.

For a file to be rendered, it has to be configured in the `doctoolchainConfig.groovy` file.
There you will find a section like the following:

```
inputFiles = [
        [file: 'manual.adoc',       formats: ['html','pdf']],
        /** inputFiles **/
]
```

Add the files which you want to be rendered along with the format. 
In this case `pdf`.

.Hint
[%collapsible]
====
Why do you need to configure the files to be rendered?

Asciidoctor renders all `.adoc` files by default, no matter if these are the main documents or just chapters you want to include.
In addition, it is quite likely that you only want to convert a few files to PDF.
Hence, you have to configure which ones.
====

== Creating a Custom PDF Theme

If you want to change colors, fonts or page headers and footers, you can do so by creating a `custom-theme.yml` file.
Copy the file `src/docs/pdfTheme/custom-theme.yml` from docToolchain to your project and reference it from your main `.adoc`file by setting the `:pdf-stylesdir:`.
For example, insert the following at the top of your document to reference `custom-theme.yml` from the `/pdfTheme` folder.

    :pdf-stylesdir: ../pdfTheme

== Further Reading and Resources

* Learn how to modify a theme by reading https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc[asciidoctor-pdf theming guide].
* The https://rdmueller.github.io/pdf-output/[Beyond HTML] blog post is also an excellent resource if you want to dig a little deeper.

== Source

.AsciiDocBasics.gradle
[source,groovy]
----
include::{projectRootDir}/scripts/AsciiDocBasics.gradle[tags=generatePDF]
----
