:filename: 015_tasks/03_task_generateContent.adoc
include::_config.adoc[]

== generateContent

include::../_feedback.adoc[]

=== About This Task

This task makes use of https://platform.openai.com[openAI] to render documentation into your input Asciidoc files.
It can help you to get started with the outline of your documentation or even with real content. This task implements OpenAI https://platform.openai.com/docs/api-reference/completions[completions].
Simply put an asciidoc comment block that starts with `AI:` followed by your description what you need.

[NOTE]
You need a valid https://platform.openai.com/account/api-keys[API-Key] from OpenAI to execute this task.
Be aware that whatever content you use to describe what you want, OpenAI will process this data!

=== Configuration

.Config.groovy
[source,groovy]
----
include::{projectRootDir}/Config.groovy[tags=openAIConfig]
----

[WARNING]
Token is a credential, it is best not to put it into your config, but pass this parameter to the task using `-PopenAI.token=xx-xxxxxxxxxxxxx` at task execution.

=== Example

Given a config in your project, that specifies the following inputFiles:

.docToolchainConfig.groovy
[source,groovy]
----
/** config redacted **/
inputFiles = [
	[file: 'example/example.adoc', formats: ['html','pdf', 'docbook']],
        /** inputFiles **/
]
/** config redacted  **/
----

You could generate a whole file, e.g. an outline for your documentation.

.example/example.adoc
[source,asciidoc]
----
////
AI: Create an outline for a documentation of a Java based microservice called fraud-detector. The documentation should follow the Divio structure. Use Asciidoc syntax for the output. The result should define a toc.
////
----

[NOTE]
The result varies based on your input you give, the more specific you are, the better suited the output.

The result could look like the following:

.example/example.adoc
[source,asciidoc]
----
= Fraud-Detector
:toc:

== Overview
* Description of fraud-detector microservice
* Abstract view of architecture
* List of core libraries used

== Getting Started
* Setup instructions
* How to add it as a dependency
* Configuration instructions

== Architecture
* In-depth view of architecture
  * Components
  * Services
  * Data Structure

== Development
* Contribution Guidelines
* Coding Standards
* Debugging Suggestions

== Troubleshooting
* Known Issues and Solutions
* Support

== FAQs
* Common Questions and Answers
----

You can also let just parts of your docs, like installation of basic tools, e.g. JDK 17, generate.
[NOTE]
You can specify as many `AI:` blocks as you want. They will al be replaced by openAI.

.example/example.adoc
[source,asciidoc]
----
== Getting Started

* Setup instructions

////
AI: Write a short how-to install JDK 17 on Windows, Mac and Linux using sdkman. Use Asciidoc syntax for the output.
////

* How to add it as a dependency
----

The example above, will lead to a result similar to:

.example/example.adoc
[source,asciidoc]
-----
= Installing JDK 17 using SDKMAN

JDK 17 is a version of the Java Development Kit that is suitable for general use. It can be installed quickly and easily with the help of SDKMAN. This guide includes instructions for installation on Windows, Mac and Linux operating systems.

== Windows

JDK 17 can be installed on Windows with the following commands:

[source,shell]
----
sdk install java 17.0.1-open
----

== Mac

JDK 17 can be installed on Mac with the following commands:

[source,shell]
----
sdk install java 17.0.1-open
----

== Linux

JDK 17 can be installed on Linux with the following commands:

[source,shell]
----
sdk install java 17.0.1-open
----
-----

== Source

:param_source_file: scripts/generateContent.gradle
:param_source_language: groovy
:param_source_tags: generateContent
include::_viewTaskSource.adoc[]
