:filename: 015_tasks/03_task_downloadTemplate.adoc
include::_config.adoc[]

[[task_downloadTemplate]]
== downloadTemplate

include::../_feedback.adoc[]

=== About This Task

This task is primarily used to bootstrap a new project. You can choose to download an official template like https://github.com/arc42/arc42-template[arc42] or https://github.com/Hruschka/req42-framework[req42] (both available in multiple languages) or you can register and use your own custom template.

=== Setup and Configuration

You can choose to bootstrap your project as an Antora project or as a plain AsciiDoc project. The Antora integration is currently in beta. The Antora integration enables you to register the project seamlessly with an existing Antora playbook.

=== experimental Antora support

* to test the Antora template
** install antora: https://docs.antora.org/antora/latest/install/install-antora/
** download the arc42 template as antora style `./dtcw downloadTemplate`
** create a `playbook.yaml` within the root of your project
** make sure that your project is a valid git repository and contains at least one commit
** execute `antora playbook.yml`

.playbook.yml
[source, yml]
----
site:
  title: Antora ARC42 Template
  start_page: arc42-template::index.adoc
content:
  sources:
  - url: ./
    start_path: src/docs/arc42
    branches: [HEAD]
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
asciidoc:
  attributes:
    sectanchors: true

output:
  dir: build/antora
----

NOTE: To install antora, follow the instructions on https://docs.antora.org/antora/latest/install-and-run-quickstart/

=== Further Reading and Resources

* https://arc42.org/[Arc42]
* https://req42.de/[Req42]
