:filename: 015_tasks/03_task_exportEA.adoc
include::_config.adoc[]

== exportEA

include::../_feedback.adoc[]

=== About This Task

By default, no special configuration is necessary.
However, several optional parameter configurations are available to support a project and packages to be used for export.
These parameters can be used independently from one another.
A sample of how to edit your projects' Config.groovy is provided in the 'Config.groovy' of the docToolchain project itself.

=== Important

Currently this feature is WINDOWS-only. See https://github.com/docToolchain/docToolchain/issues/231[this related issue].

=== The Optional Parameter Configurations

==== connection
Either set the connection to a certain project, or comment it out to use all project files inside the src folder or its child folder.

==== packageFilter
Add one or multiple packageGUIDs to be used for export. All packages are analysed, if no packageFilter is set.

==== exportPath
Relative path to base 'docDir' to which the diagrams and notes are to be exported.
Default: "src/docs".
Example: docDir = 'D:\work\mydoc\' ; exportPath = 'src/pdocs' ;
Images will be exported to 'D:\work\mydoc\src\pdocs\images\ea',
Notes will be exported to 'D:\work\mydoc\src\pdocs\ea',

==== searchPath
Relative path to base 'docDir', in which Enterprise Architect project files are searched
Default: "src/docs".
Example: docDir = 'D:\work\mydoc\' ; exportPath = 'src/projects' ;
Lookup for eap and eapx files starts in 'D:\work\mydoc\src\projects' and goes down the folder structure.
*Note*: In case parameter 'connection' is already defined, the searchPath value is also used.
exportEA starts opening the database parameter 'connection' first then looks for
further project files either in the searchPath (if set) or in the docDir folder of the project.

==== glossaryAsciiDocFormat
Whether or not the EA project glossary is exported depends on this parameter.
If not set or an empty string, no glossary is exported.
The glossaryAsciiDocFormat string is used to format each glossary entry in a
certain AsciiDoc format.

The following placeholders are defined for the format string: ID, TERM, MEANING, TYPE.
One or more can be used by the output format. For example:

A valid output format is to include the glossary as a flat list.
The file can be included where needed in the documentation.
....
glossaryAsciiDocFormat = "TERM:: MEANING"
....
Other format strings can be used to include it as a table row.
The glossary terms are sorted in alphabetical order.

==== glossaryTypes
This parameter is used in case a glossaryAsciiDocFormat is defined, otherwise it
is not evaluated. It's used to filter for certain types.
If the glossaryTypes list is empty, all entries will be used.
For example:

glossaryTypes = ["Business", "Technical"]

==== diagramAttributes
If set, the string is used to create and store diagram attributes to be included in the document alongside a diagram.
These placeholders are defined and populated with the diagram attributes, if used in the
diagramAttributes string:

`%DIAGRAM_AUTHOR%`, +
`%DIAGRAM_CREATED%`, +
`%DIAGRAM_GUID%`, +
`%DIAGRAM_MODIFIED%`, +
`%DIAGRAM_NAME%`, +
`%DIAGRAM_NOTES%`, +
`%DIAGRAM_DIAGRAM_TYPE%`, +
`%DIAGRAM_VERSION%`, +
`%NEWLINE%` +

Example: diagramAttributes = "Last modification: %DIAGRAM_MODIFIED%%NEWLINE%Version: %DIAGRAM_VERSION%"

You can add the string %NEWLINE% where a line break will be added.
The resulting text is stored next to the diagram image using the same path and file name, but a different file extension (.ad). This can be included in the document if required.
If diagramAttributes is not set or an empty string, no file is written.

==== additionalOptions
This parameter is used to define the specific behavior of the export. Currently these options are supported:

`KeepFirstDiagram`

If diagrams are not uniquely named, the last diagram will be saved. If you want to prevent diagrams from being overwritten, add this parameter to additionalOptions.

=== Glossary export
By setting the glossaryAsciiDocFormat, the glossary terms stored in the EA project
will be exported into a folder named 'glossary' below the configured exportPath.
In case multiple EA projects are found for export, one glossary per project is
exported - each named using the project's GUID plus extension '.ad'.

Each individual file will be filtered (see glossaryTypes) and sorted in alphabetical order.
In addition, a global glossary is created by using all single glossary files.
This global file is named 'glossary.ad' and is also placed in the glossary folder.
The global glossary is also filtered and sorted.
If there is only one EA project, only the global glossary is written.

=== Further Reading and Resources
* https://rdmueller.github.io/jria2eac/[JIRA to Sparx EA] blog post.
* https://rdmueller.github.io/sparx-ea/[Did you Ever Wish you Had Better Diagrams?] blog post.

=== Source

:param_source_file: scripts/exportEA.gradle
:param_source_language: groovy
:param_source_tags: exportEA
include::_viewTaskSource.adoc[]

:param_source_file: scripts/exportEAP.vbs
:param_source_language: vbscript
include::_viewTaskSource.adoc[]
