= {project-name} Changelog
:project-name: asciidoctor-reveal.js
:uri-repo: https://github.com/asciidoctor/asciidoctor-reveal.js
:uri-issue: {uri-repo}/issues/

This document provides a high-level view of the changes introduced in {project-name} by release.
For a detailed view of what has changed, refer to the {uri-repo}/commits/master[commit history] on GitHub.

== Master branch

Enhancements::
  * Documentation improvements

Compliance::
  * Added `data-state: title` to the title slide ({uri-issue}123[#123])

Bug fixes::
  * Fixed consistency issues with boolean values handling in revealjs settings ({uri-issue}125[#125])

////
Infrastructure::
  * item

=== Release meta

{uri-repo}/issues?q=milestone%3A1.0.2[issues resolved] |
{uri-repo}/releases/tag/v1.0.2[git tag] |
{uri-repo}/compare/v1.0.1...v1.0.2[full diff]

=== Credits

Thanks to the following people who contributed to this release:

...
////


== 1.0.2 (2016-12-22) - @obilodeau

Enhancements::
  * Ruby back-end is now compiled in Javascript with Opal (#115)
  * Documentation improvements

=== Release meta

{uri-repo}/issues?q=milestone%3A1.0.2[issues resolved] |
{uri-repo}/releases/tag/v1.0.2[git tag] |
{uri-repo}/compare/v1.0.1...v1.0.2[full diff]

=== Credits

Thanks to the following people who contributed to this release:

Dan Allen, Guillaume Grossetie, Olivier Bilodeau


== 1.0.1 (2016-10-12) - @obilodeau

Enhancements::
  * Documentation: aligned release process for both npm and ruby gems packages
  * npm package in sync with ruby gem

=== Release meta

Released by @obilodeau

{uri-repo}/issues?q=milestone%3A1.0.1[issues resolved] |
{uri-repo}/releases/tag/v1.0.1[git tag] |
{uri-repo}/compare/v1.0.0...v1.0.1[full diff]

=== Credits

Thanks to the following people who contributed to this release:

Olivier Bilodeau


== 1.0.0 (2016-10-06) - @obilodeau

Since this is the first ever "release" of asciidoctor-reveal.js (we used to do continuous improvements w/o releases in the past), this list focuses on the major enhancements introduced over the last few weeks.

Enhancements::
  * Initial release
  * Ruby package (#93)
  * Node package (#95)
  * `:customcss:` attribute for easy per-presentation CSS (#85)
  * Video support improvements (#81)
  * Reveal.js `data-state` support (#61)
  * Subtitle partioning (#70)
  * Background image rework (#52)
  * `:imagesdir:` properly enforced (#17, #67)

=== Release meta

Released by @obilodeau

{uri-repo}/issues?q=milestone%3A1.0.0[issues resolved] |
{uri-repo}/releases/tag/v1.0.0[git tag]

=== Credits

Thanks to the following people who contributed to this release:

Alexander Heusingfeld, Andrea Bedini, Antoine Sabot-Durand, Brian Street, Charles Moulliard, Dan Allen, Danny Hyun, Emmanuel Bernard, gtoast, Guillaume Grossetie, Jacob Aae Mikkelsen, Jakub Jirutka, Jozef Skrabo, Julien Grenier, Julien Kirch, kubamarchwicki, lifei, Nico Rikken, nipa, Olivier Bilodeau, Patrick van Dissel, phrix32, Rahman Usta, Robert Panzer, Rob Winch, Thomas and Wendell Smith
