:filename: 030_news/2023/2.2.0-release.adoc
:jbake-title: Release v2.2.0
:jbake-date: 2023-02-15
:jbake-type: post
:jbake-tags: docToolchain
:jbake-status: published
:jbake-menu: -
:jbake-author: Ralf D. Müller
:icons: font

ifndef::imagesdir[:imagesdir: ../../../images]

== docToolchain v2.2.0 has Been Released!

=== About This Release

This is a fresh release of many nice features. 
The best probably is the `exportConfluence` Task which lets you export a whole confluence space to AsciiDoc!

To test the new release, the docToolchain wrapper `dtcw` will not be updated until the end of the week.

To discuss the new features, a new https://github.com/docToolchain/docToolchain/discussions/1020[discussion thread] has been created.

IMPORTANT: please take a close look at the changelog, because there are some breaking changes

== Changes which need migration

* https://github.com/docToolchain/docToolchain/issues/937[#937 Confluence publish nested pages by heading]
+
This replaces the settings `allInOnePage` and `createSubPages`.
Migrate as follows:
+
** `allInOnePage = true` is the same as `subpagesForSections = 0`
** `allInOnePage = false && createSubpages = false` is the same as `subpagesForSections = 1`
** `allInOnePage = false && createSubpages = true` is the same as `subpagesForSections = 2`

* https://github.com/docToolchain/docToolchain/issues/940[#940 simplify configuration to use preamble heading from h1 instead of configuration]
+
Migrate by removing the setting `preambleTitle` and set the correct first level heading in the document.
* Make `dtcw` (and some other shell executables) https://www.shellcheck.net/[shellcheck] proof

IMPORTANT: the docker image has been moved to **doctoolchain**/doctoolchain:v2.2.0

NOTE: a big "THANK YOU" to all *Sponsors* and *Contributors* who helped to support docToolchain!

You like docToolchain? 
What about helping to make it even better? 
docToolchain is a community project, so be part of the community which drives the project. 
You don't have to code for doing so. 
It would even help to brush up the docs, write tutorials or groom the backlog 
(I guess many of the open issues are already fixed).


== 2.2.0 - 2023-02-16

=== fixes

* fixed whitespace in GH issue template (which leads to errors in `htmlSanityCheck`)
* fixed ExportMarkdownSpec
* fixed GenerateDeckSpec
* fixed GenerateDeck / Reveal.js
* fixed exportEA hangs by EA v16.1
* fixed exportEA write model notes into models subfolder
* allow numeric ancestorIds for confluence export
* https://github.com/docToolchain/docToolchain/pull/951[#951 Improve DTC_PROJECT_BRANCH management]
* https://github.com/docToolchain/docToolchain/issues/976[#976 dtcw shows a fatal error when not in git repository]
* https://github.com/docToolchain/docToolchain/issues/978[#978 dtcw.ps1 does not correctly check for java version]
* https://github.com/docToolchain/docToolchain/issues/890[#890 updated documentation on "Self-Contained docToolchain"]
* Remove never used analytics.js file from docsy theme

=== added

* new Task exportConfluence
* Add `confluenceBearerToken` property
* rubyExtensions configuration
* CZ as language for downloadTemplate
* Enable to use a particular version of DTC from the wrapper by setting the environment variable 'DTC_VERSION' accordingly.
* https://github.com/docToolchain/docToolchain/issues/1002[publishToConfluence: Add possibility to set the page version comment]
* exportEAP.vbs: trim notes filename
* exportEAP.vbs: creates for each model a combined notes
* exportEAP.vbs: msg "looking for..." extended for EA 16.1

=== changed

* switch docker base image from deprecated openJDK 14 to temurin 11
* The `publishToConfluence` guide now contains 3 modes for authentication (username & password, username & API key, personal access token)
* Improve confluence export performance when only ancestorIds are given
* https://github.com/docToolchain/docToolchain/issues/937[#937 Confluence publish nested pages by heading]
+
This replaces the settings `allInOnePage` and `createSubPages`.
Migrate as follows:
+
** `allInOnePage = true` is the same as `subpagesForSections = 0`
** `allInOnePage = false && createSubpages = false` is the same as `subpagesForSections = 1`
** `allInOnePage = false && createSubpages = true` is the same as `subpagesForSections = 2`

* https://github.com/docToolchain/docToolchain/issues/683[#683 publishToConfluence with unknown source language]
* https://github.com/docToolchain/docToolchain/issues/940[#940 simplify configuration to use preamble heading from h1 instead of configuration]
+
Migrate by removing the setting `preambleTitle` and set the correct first level heading in the document.
* Make `dtcw` (and some other shell executables) https://www.shellcheck.net/[shellcheck] proof
