:jbake-rightColumnHtml: <a href="single-page.html"><i class="fa fa-file fa-fw"></i> View single page</a>
//tag::install[]

:filename: 010_manual/20_install.adoc
:icons: font

= Installing docToolchain

include::../_feedback.adoc[]

== Getting the Wrapper

There have been a few changes to the way docToolchain can be installed since its V2.x release. We built a simple wrapper script to takes care of the everything for you.

This wrapper helps you in the following ways:

- it ensures that everyone who uses your repository is using the same version of docToolchain.
- it keeps all the docToolchain technology out of your repository.
- it wraps all of your commands and directs them to your local docToolchain installation.
- furthermore, it checks how you installed docToolchain. If it hasn't been installed yet, it will do so for you via direct download or docker.

This installation guide will show you how to set up docToolchain in the following environments:

- A Linux/WSL2 with bash
- Windows with PowerShell and
- Windows with cmd.exe

Please select the appropriate setup and follow these instructions to install docToolchain step by step.

.Linux / WSL2 with bash
[role='primary']
--
[source, bash]
----
cd <your project>
wget doctoolchain.github.io/dtcw
chmod +x dtcw
----

if you don't have `wget` installed, you can also use `curl`:
[source, bash]
----
cd <your project>
curl -Lo dtcw doctoolchain.github.io/dtcw
chmod +x dtcw
----

--

.Windows with Powershell
[role='secondary']
--
[source, powershell]
----
cd <your project>
Invoke-WebRequest doctoolchain.github.io/dtcw.ps1 -Outfile dtcw.ps1
----
--

.Windows with cmd.exe
[role='secondary']
--
[source, cmd]
----
cd <your project>
curl -Lo dtcw.bat doctoolchain.github.io/dtcw.bat
----

NOTE: `dtcw.bat` wraps the `dtcw.ps1` script and executes it in powershell. This might be easier to use if you haven't yet configured your powershell as a developer.

--

NOTE: In order to support development for your project on both, Linux and Windows, it makes sense to download all three scripts to your project.

NOTE: if you use `cmd.exe`, please refer and follow the instructions for powershell. We will not further differentiate between both. You should however replace `.ps1` with `.bat`.

IMPORTANT: `dtcw` uses bash as shell and thus tries to find java from within bash. Chances are that when you use `dtcw` from another shell like zsh, you shell knows about the right java version but your bash doesn't. In that case, please switch to bash and make sure that the right java version is known. Afterwards, you can switch back to your shell.



== Running your first command

To get started with docToolchain, you can run `tasks` as a first command:

.Linux / WSL2 with bash
[role='primary']
--
[source, bash]
----
./dtcw tasks --group=doctoolchain
----
--

.Windows with Powershell
[role='secondary']
--
[source, powershell]
----
./dtcw.ps1 tasks --group=doctoolchain
----

NOTE: if you're making use of cmd.exe, please replace `.ps1` with `.bat`. Do this for subsequent commands.

--

This 'tasks' command display you all of the tasks available on docToolchain. It also verify that docToolchain is installed by:

* Checking for a configuration file. It will creates a default one if none is available. It prefers a local installation. 

* Making use of docker if it is available and there is no local installation. Please keep in mind that if this is your first time running docToolchain, the images download could take a while.

* if docker is not available, it will download and install docToolchain to your home folder
** it will then run a gradle build through the gradle wrapper. If this is your first time, It will download and install gradle.
** the gradle build will also fetch some dependencies. This will also take a while if ran for the first time.

You'll notice the installation is an incremental process and will take a while because of all the additional dependencies needed.
After the first few commands, you'll have all the needed dependencies installed and things will run more quickly.

//end::install[]

== Existing documents

If your project already has some existing documents in AsciiDoc format, you'll need to tell docToolchain where it can find it.

To do so, take a look at the created `docToolchainConfig.groovy` and update it.

== arc42 from scratch

If you don't have existing documents yet, or if you need a fresh start, you can get the https://arc42.org[arc42] template in AsciiDoc format.

Run the command below to tell docToolchain to download the template of your choice:

.Linux / WSL2 with bash
[.primary]
--
[source,bash]
----
./dtcw downloadTemplate
----
--

.Windows
[.secondary]
--
[source,powershell]
----
./dtcw.ps1 downloadTemplate
----
--

== Build: Creating Templates.

By now, the docToolchain wrapper `dtcw` should be in your project folder along with the arc42 template.

Let's now render it as HTML and PDF. Run the commands below to execute this:

.Linux / WSL2 with bash
[.primary]
--
[source,bash]
----
./dtcw generateHTML
./dtcw generatePDF
----
--

.Windows
[.secondary]
--
[source,powershell]
----
./dtcw.ps1 generateHTML
./dtcw.ps1 generatePDF
----
--

As a result, you will see the progress of your build together with some warnings which you can just ignore for the moment.

The first build generated some files within the `build`:

[source]
----
build
|-- html5
|   |-- arc42
|   |   `-- arc42.html
|   `-- images
|       |-- 05_building_blocks-EN.png
|       |-- 08-Crosscutting-Concepts-Structure-EN.png
|       `-- arc42-logo.png
`-- pdf
    |-- arc42
    |   `-- arc42.pdf
    `-- images
        |-- 05_building_blocks-EN.png
        |-- 08-Crosscutting-Concepts-Structure-EN.png
        `-- arc42-logo.png
----

*Congratulations!* If you see the same folder structure, you've just render the standard arc42 template as html and pdf!

Please raise an issue on https://github.com/docToolchain/docToolchain/issues[github] if you didn't get the right output.

TIP: Blog-Posts: https://rdmueller.github.io/enterprise-edition/[Behind the great Firewall], https://rdmueller.github.io/enterprise-edition2/[Enterprise AsciiDoctor]

