#!/usr/bin/env groovy
// @task
// v4: Scaffold a docToolchain CI/CD pipeline (dtcw4-based) for GitHub or GitLab

def docDir = System.getProperty('docDir', '.')
def scriptDir = System.getProperty('dtc.scriptsHome') ? new File(System.getProperty('dtc.scriptsHome')) : new File(getClass().protectionDomain.codeSource.location.toURI()).parentFile
def gcl = new GroovyClassLoader(this.class.classLoader)
gcl.parseClass(new File(scriptDir, 'lib/DtcException.groovy'))
def DtcError = gcl.loadClass('DtcError')
def DtcException = gcl.loadClass('DtcException')

def color = { c, text ->
    def colors = [red: 31, green: 32, yellow: 33, cyan: 36]
    return new String((char) 27) + "[${colors[c]}m${text}" + new String((char) 27) + "[0m"
}

// Single top-level handler (ADR-8): the body throws DtcException with guidance.
// Body kept un-indented to minimise the diff (Groovy is not whitespace-sensitive).
try {

println "docToolchain v4 — generateCICD"

// --- Args: provider + --force ----------------------------------------------
def args = this.args as List
def provider = (args.find { it.startsWith('--provider') }?.replaceAll(/^--provider[=\s]*/, '')
        ?: args.find { !it.startsWith('-') }
        ?: 'github').toLowerCase()
def force = args.contains('--force')

// dtcw4 bootstraps the v4 runtime in CI: clone-free, no Gradle, no v3 image.
def java = '25'

def githubWorkflow = """\
# Generated by 'dtcw4 generateCICD'. Builds the docToolchain microsite with dtcw4
# and publishes it to GitHub Pages. Enable Pages (Settings > Pages > Source:
# GitHub Actions) for the deploy job to succeed.
name: Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment.
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '${java}'
      - name: Cache docToolchain
        uses: actions/cache@v4
        with:
          path: ~/.doctoolchain
          key: dtc-\${{ runner.os }}-\${{ hashFiles('docToolchainConfig.groovy') }}
          restore-keys: dtc-\${{ runner.os }}-
      - name: Install docToolchain
        run: |
          curl -Lo dtcw4 https://doctoolchain.org/dtcw4
          chmod +x dtcw4
          ./dtcw4 local install doctoolchain
      - name: Generate site
        run: ./dtcw4 local generateSite
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/microsite/output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
"""

def gitlabCi = """\
# Generated by 'dtcw4 generateCICD'. Builds the docToolchain microsite with dtcw4
# and publishes it via GitLab Pages (expects the output in ./public).
image: eclipse-temurin:${java}-jdk

stages:
  - build

pages:
  stage: build
  cache:
    key: doctoolchain
    paths:
      - .doctoolchain/
  variables:
    DTC_HOME: \${CI_PROJECT_DIR}/.doctoolchain
  script:
    - curl -Lo dtcw4 https://doctoolchain.org/dtcw4
    - chmod +x dtcw4
    - ./dtcw4 local install doctoolchain
    - ./dtcw4 local generateSite
    - rm -rf public && mv build/microsite/output public
  artifacts:
    paths:
      - public
  rules:
    - if: \$CI_COMMIT_BRANCH == \$CI_DEFAULT_BRANCH
"""

def targets = [
    github: [path: '.github/workflows/docs.yml', content: githubWorkflow, label: 'GitHub Actions'],
    gitlab: [path: '.gitlab-ci.yml', content: gitlabCi, label: 'GitLab CI'],
]

def target = targets[provider]
if (!target) {
    throw DtcException.newInstance("Unknown provider '${provider}'. Use one of: ${targets.keySet().join(', ')}")
}

def outFile = new File(docDir, target.path)
if (outFile.exists() && !force) {
    throw DtcException.newInstance(
        "${target.path} already exists — refusing to overwrite. Re-run with --force to replace it.")
}

outFile.parentFile?.mkdirs()
outFile.setText(target.content, 'UTF-8')
println "${color('green', "Wrote ${target.label} pipeline to ${target.path}")}"
println ""
println "Next steps:"
if (provider == 'github') {
    println "  - Commit ${target.path}"
    println "  - Enable GitHub Pages: Settings > Pages > Source: GitHub Actions"
} else {
    println "  - Commit ${target.path}"
    println "  - The 'pages' job publishes to GitLab Pages on the default branch"
}

} catch (Throwable t) {
    System.exit(DtcError.report(t))
}
