:filename: 025_development/020_run_tests.adoc
== Running Tests

include::../_feedback.adoc[]

=== Prerequisites

- make sure that Git and Graphviz are installed
- make sure that your Gradle setup is able to work with proxies
- use Java 8

=== Prepare the Project

[source,bash]
----
git clone git@github.com:docToolchain/docToolchain.git
cd docToolchain/
git checkout V1.0.0         # <1>
git submodule update -i
----

<1> the version to test.
Not needed if you work on the HEAD revision on Master

=== Execute Tests

[source,bash]
----
rm -r build && ./gradlew test --info
----

The `rm` command ensures that you really have a clean test running.
Otherwise you might get false positives because Gradle will skip steps ('Up-to-date') because artifacts of an older test run still exist.

=== Proxy Setting for Tests

The docToolchain test setup is based on the https://docs.gradle.org/current/userguide/test_kit.html[Gradle-Test-Kit] and makes use of the  https://code.google.com/archive/p/spock/[Spock test execution framework].

The gradle test runner is started in its own test environment and its own JVM instance.
As a result the global proxy settings are ignored.

As workarund to execute the test with the correct proxy settings it is necessary to copy the proxy setting normally done in the in gradle.properties located in the user directory to the gradle.properties file located in the docToolchain folder itself.

NOTE: The files downloaded by the Gradle test Runner are placed in a different folder than the default gradle cache. You'll find them in the Tmp folder: C:\Users\YOUR_USER_NAME\AppData\Local\Temp\.gradle-test-kit-YOUR_USER_NAME\caches
