== Create new Release

include::../_feedback.adoc[]

We use https://semver.org/[semantic versioning] and https://keepachangelog.com/[keep a changelog]. Bot on a best effort base.

A release consists of four parts:

=== Github

* update version in `gradle.properties`
* update the changelog
** create a section for the version
** copy all unreleased features which will be in the release to the created section
** commit and push the new version
* https://github.com/docToolchain/docToolchain/releases/new[Draft a new release]
* copy the content of the changelog for this version to the description and submit
* set version as **v**X.Y.Z
* run `./gradlew createDist`
* this creates a zip of the source in `build` which is the distribution file
* add this zip and submit the new release

=== docToolchain-Wrapper (dtcw)

* update the version used in the wrapper
** https://github.com/docToolchain/doctoolchain.github.io/blob/master/dtcw[dtcw]
** https://github.com/docToolchain/doctoolchain.github.io/blob/master/dtcw.ps1[dtcw.ps1]

=== Dockerhub

The image build for https://hub.docker.com/repository/docker/rdmueller/doctoolchain[rdmueller/doctoolchain] depends on the github repository https://github.com/docToolchain/docker-image[docToolchain/docker-image]

* update the https://github.com/docToolchain/docker-image/tree/master/alpine[Dockerfile] to reflect the new version
* create a https://github.com/docToolchain/docker-image/releases/new[new release]
* reference the github release for changelog
* the build on dockerhub will be automatically triggered

IMPORTANT: currently, the autobuild only works for paying customers. +
To manually build and upload the image, download the repository, switch to branch `ng-beta`, cd to the `alpine` folder and execute `docker build -t rdmueller/doctoolchain:v2.0.0-rc15 .`. Afterwards use docker desktop to push the resulting image to the hub.

=== sdkman

A github action has been created to deploy to sdkman: https://github.com/docToolchain/docToolchain/actions?query=workflow%3A%22sdkman+deploy%22[sdkman deploy].

* set version to the same as for the other relases but without the pre-pended _v_: X.Y.Z
* use as download link the link to the `docToolchain-dist.zip` from the github release (hint: looks like  https://github.com/docToolchain/docToolchain/releases/download/v1.3.1/docToolchain-dist.zip)
