:filename: 025_development/030_create_new_release.adoc
== Creating a New Release

include::../_feedback.adoc[]

=== Before You Begin

- We use https://semver.org/[semantic versioning] and we also keep a https://keepachangelog.com/[changelog]. All of this is done on a best-efforts basis.
- A release consists of five parts, each explained below.

=== GitHub

* Update the version in `gradle.properties`.
* Update the changelog.
	** Create a section for the version.
	** Copy to the new section all unreleased features which will be in the release.
	** Commit and push the new version.
* https://github.com/docToolchain/docToolchain/releases/new[Draft a new release].
* Copy the contents of the changelog for this version to the description then submit.
* Set the version as **v**X.Y.Z.
* Run `./gradlew createDist` to zip the source in build (the distribution file).
* Add the zipped file and submit the new release.

=== Docker Hub

==== Standard Image

The image build for https://hub.docker.com/repository/docker/rdmueller/doctoolchain[rdmueller/doctoolchain] depends on the GitHub repo https://github.com/docToolchain/docker-image[docToolchain/docker-image].

* Update the https://github.com/docToolchain/docker-image/tree/master/alpine[Dockerfile] to reflect the new version.
* Create a https://github.com/docToolchain/docker-image/releases/new[new release].
* Reference the GitHub release in the changelog (the build on Dockerhub will be automatically triggered).

Important! Currently, the autobuild only works for paying customers. To manually build and upload the image, download the repo, switch to branch `ng-beta`, cd to the `alpine` folder and execute `docker build -t rdmueller/doctoolchain:v2.0.0-rc15 .`. After that, use Docker Desktop to push the resulting image to Docker Hub.

==== Jenkins CI Image

update the version in the https://github.com/docToolchain/docker-image/actions/runs/2787848816/workflow[github action definition] and run the action.

=== Blog Post

Create a blog post to announce the new release. The SDKMAN! announcement will reference it.

=== docToolchain-Wrapper (dtcw)

Everything went well? Great! Now let’s update the wrapper.
The source of the rapper is now the main repository and we need to copy it over to the github pages.
To do so, make sure that dtcw references the right version.

* https://github.com/docToolchain/doctoolchain/blob/ng/dtcw[dtcw]
* https://github.com/docToolchain/doctoolchain/blob/ng/dtcw.ps1[dtcw.ps1]
* the dtcw.bat will be generated

then navigate to https://github.com/docToolchain/doctoolchain.github.io/actions/workflows/update-dtcw.yml and trigger the action.


=== SDKMAN!

A GitHub action https://github.com/docToolchain/docToolchain/actions?query=workflow%3A%22sdkman+deploy%22[sdkman deploy] has been created to deploy to SDKMAN!

* Set the version to the same as for the other releases, but without the prepended v: X.Y.Z.
* Use as a download link the link to the `docToolchain-dist.zip` from the GitHub release. Tip: the link looks like https://github.com/docToolchain/docToolchain/releases/download/v1.3.1/docToolchain-dist.zip[https://github.com/docToolchain/docToolchain/releases/download/v1.3.1/docToolchain-dist.zip].
