:filename: 025_development/08_development.adoc
ifndef::imagesdir[:imagesdir: ../images]

= Development

include::../_feedback.adoc[]

INFO: this chapter is still work in progress

== Setup Development Environment

Since v2.0, all the code is hidden from curious eyes when you install docToolchain.
To access and change the code, you first have to know some details about the inner workings.

=== local install, docker, sdkman

Development is based on the local installation of docToolchain.
Docker simply contains a local install and sdkman install docToolchain locally, but the location is controller by sdkman and not docToolchain.
This is why you need a local installation for development.
Docker and sdkman are derived from it.

The docToolchain-Wrapper installs docToolchain locally to `$HOME/.doctoolchain/docToolchain-${VERSION}/`.

All task invokations through the docToolchain wrapper `dtcw` are redirected to `$HOME/.doctoolchain/docToolchain-${VERSION}/bin/doctoolchain`.
This is another shell script which calls the gradle wrapper for most tasks.

So create a local install which is connected to your github fork of docToolchain, create a folder called

`$HOME/.doctoolchain/docToolchain-2.0.0-dev/`

and checkout the ng-branch of your fork to this folder.

To use this version in your test project, edit the version configured at the start of your `dtcw` script to `2.0.0-dev`.

NOTE: you have now the full repository locally cloned.
To save memory, only some parts of this repository are zipped for distribution.
Check out the https://github.com/docToolchain/docToolchain/blob/master/build.gradle#L79[prepareDist-Task] if you run into problems.

=== Create Gradle independent tasks

Currently, all tasks use Gradle to run.
To make docToolchain faster, it makes sense to circumvent Gradle for tasks where it doesn't add any benefits.
To do so, you can use the `bin/doctoolchain` scripts and create a switch.

=== Create or Change a Theme

Not only the docToolchain code but also the themes for the static site generator jBake are hidden.

==== Overwrite Theme for a Project

When docToolchain builds the static website, it first copies an internal theme to a temp-folder, then copies an external theme (if defined) over it and as a last step, it copies the project theme over it.

This gives you the chance to overwrite some parts of the theme on a per project basis.
To make it easier, run the `copyThemes` task.
It will copy the internal and external theme to `microsite.siteFolder`.
You can then check those files (take a look at https://jbake.org[jbake.org] to get a better understanding), modify the ones you wish to change and delete all others.

==== Create a new Theme

An external theme is in fact just a zipped copy of the `microsite.siteFolder` as mentioned in the previous chapter.
All themes are once downloaded when referenced from a `dtcw` configuration and are stored in `$HOME/.doctoolchain/themes/[hash of url]`.

If you want to modify an existing theme, go to its folder and checkout the theme's project instead of the downloaded copy.
This will give you the connection back to the github repository and you can modify the theme directly in `$HOME/.doctoolchain/themes/[hash of url]`.

If you want to create a new theme from scratch, the hash is a simple md5 hash.
So, for example, if you configure your new theme as `"myTheme"`, then `"myTheme".md5()` will be the hash.

==== Special functionality for Themes

===== Config Fragments

It is quite likely that you need a new config item for your self generated theme.
And wouldn't it be nice if the user would be asked to set a value for this new config item when she installs the theme for the first time?

Create a file `configFragment.groovy` in the `site` folder of your theme.
Here is an example for what to put in this file:

[source, groovy]
----
// the title of the microsite, displayed in the upper left corner
// Example: my new site
title = '##site-title##'
----

The first line is some explanation displayed to the user.
You can have several lines of explanations.

The second line, starting with `Example:` is used as default value for the prompt.

The third line is the config item itself.
If the value is surrounded by `##`, the user will be prompted for this value and it will be replaced with the user's input.
Otherwise, the config item will be added without a prompt to the users current `docToochainConfig.groovy`.

== How to run Tests

=== Prerequisites

- make sure that Git and Graphviz are installed
- make sure that your Gradle setup is able to work with proxies
- use Java 8

=== Prepare the Project

[source,bash]
----
git clone git@github.com:docToolchain/docToolchain.git
cd docToolchain/
git checkout V1.0.0         # <1>
git submodule update -i
----

<1> the version to test.
Not needed if you work on the HEAD revision on Master

=== Execute Tests

[source,bash]
----
rm -r build && ./gradlew test --info
----

The `rm` command ensures that you really have a clean test running.
Otherwise you might get false positives because Gradle will skip steps ('Up-to-date') because artifacts of an older test run still exist.

=== Proxy Setting for Tests

The docToolchain test setup is based on the https://docs.gradle.org/current/userguide/test_kit.html[Gradle-Test-Kit] and makes use of the  https://code.google.com/archive/p/spock/[Spock test execution framework].

The gradle test runner is started in its own test environment and its own JVM instance.
As a result the global proxy settings are ignored.

As workarund to execute the test with the correct proxy settings it is necessary to copy the proxy setting normally done in the in gradle.properties located in the user directory to the gradle.properties file located in the docToolchain folder itself.

NOTE: The files downloaded by the Gradle test Runner are placed in a different folder than the default gradle cache. You'll find them in the Tmp folder: C:\Users\YOUR_USER_NAME\AppData\Local\Temp\.gradle-test-kit-YOUR_USER_NAME\caches

== Create new Release

We use https://semver.org/[semantic versioning] and https://keepachangelog.com/[keep a changelog]. Bot on a best effort base.

A release consists of four parts:

=== Github

* update version in `gradle.properties`
* update the changelog
** create a section for the version
** copy all unreleased features which will be in the release to the created section
** commit and push the new version
* https://github.com/docToolchain/docToolchain/releases/new[Draft a new release]
* copy the content of the changelog for this version to the description and submit
* set version as **v**X.Y.Z
* run `./gradlew createDist`
* this creates a zip of the source in `build` which is the distribution file
* add this zip and submit the new release

=== docToolchain-Wrapper (dtcw)

* update the version used in the wrapper
** https://github.com/docToolchain/doctoolchain.github.io/blob/master/dtcw[dtcw]
** https://github.com/docToolchain/doctoolchain.github.io/blob/master/dtcw.ps1[dtcw.ps1]

=== Dockerhub

The image build for https://hub.docker.com/repository/docker/rdmueller/doctoolchain[rdmueller/doctoolchain] depends on the github repository https://github.com/docToolchain/docker-image[docToolchain/docker-image]

* update the https://github.com/docToolchain/docker-image/tree/master/alpine[Dockerfile] to reflect the new version
* create a https://github.com/docToolchain/docker-image/releases/new[new release]
* reference the github release for changelog
* the build on dockerhub will be automatically triggered

=== sdkman

A github action has been created to deploy to sdkman: https://github.com/docToolchain/docToolchain/actions?query=workflow%3A%22sdkman+deploy%22[sdkman deploy].

* set version to the same as for the other relases but without the pre-pended _v_: X.Y.Z
* use as download link the link to the `docToolchain-dist.zip` from the github release (hint: looks like  https://github.com/docToolchain/docToolchain/releases/download/v1.3.1/docToolchain-dist.zip)

== Debugging

Sometimes things go are different than expected and you need to find out what's wrong.
Here are some tips that might help you.

=== General Advice

To dig deeper into the workings of docToolchain, it makes sense that you setup yourself a development environment.
This gives you the chance to add extra debug output to the tasks which you want to inspect.

=== Gradle

You get most hints on what is going on in regards to gradle when you add the `--info` flag to your command.

`./dtcw generateSite --info`

This will output all configuration settings as seen by docToolchain and many more internal bits.

=== jBake Templates

If something goes wrong within a template, you often get not much information.
Take a look at `menu.gsp` to see how you can use `try/catch` blocks to get an error message.
But to find out _where_ the problem occurs, you need to use poor mans debugger and add some `System.out.println` statements.
Make sure that you use the full `System.out.println` statement and not only `println`.
Otherwise, you will see no output.

=== Theming / Menu / Images

It might seem a bit like magic how the system creates the menu entries.
Sometimes you don't find the reason why an image is not shown.
Remember, that you can check out the generated files.

Check the `build/microsite/tmp` folder to see the folder which is fed into jBake.
In this folder, all files will have additional `jbake` attributes which are used to build the menu.
They are generated from the original attributes of the file and folder/filename information.

Check the `build/microsite/output` folder to see the generated result.
This often helps to check where an image actually is located.

