branch = System.getenv("DTC_PROJECT_BRANCH")
// the title of the microsite, displayed in the upper left corner
title = '##site-title##'
// the next items configure some links in the footer
//
// contact eMail
// example: mailto:bert@example.com
footerMail = '##footer-email'
//
// twitter account url
footerTwitter = '##twitter-url##'
//
// Stackoverflow QA
footerSO = '##Stackoverflow-url##'
//
// Github Repository
footerGithub = '##Github-url##'
//
// Slack Channel
footerSlack = '##Slack-url##'
//
// Footer Text
// example: <small class="text-white">built with docToolchain and jBake <br /> theme: docsy</small>
footerText = '##Footer-Text##'
// site title if no other title is given
title = 'docToolchain'
//
// the url to create an issue in github
// Example: https://github.com/docToolchain/docToolchain/issues/new
issueUrl = '##issue-url##'
//
// the base url for code files in github
// Example: https://github.com/doctoolchain/doctoolchain/edit/${branch}/content/src/docs/
gitRepoUrl = '##git-repo-url##'
//
// the location of the landing page
landingPage = 'landingpage.gsp'
// the menu of the microsite. A map of [code:'title'] entries to specify the order and title of the entries.
// the codes are autogenerated from the folder names or :jbake-menu: attribute entries from the .adoc file headers
// use [code:'-'] to exclude a code from the menu
menu = [:]
