// the title of the microsite, displayed in the upper left corner
title = '##site-title##'
// the next items configure some links in the footer
//
// contact eMail
// example: mailto:bert@example.com
footerMail = '##footer-email'
//
// twitter account url
footerTwitter = '##twitter-url##'
//
// Stackoverflow QA
footerSO = '##Stackoverflow-url##'
//
// Github Repository
footerGithub = '##Github-url##'
//
// Slack Channel
footerSlack = '##Slack-url##'
//
// the location of the landing page
landingPage = 'landingpage.gsp'
// the menu of the microsite. A map of [code:'title'] entries to specify the order and title of the entries.
// the codes are autogenerated from the forlder names or :jbake-menu: attribute entries from the .adoc file headers
menu = [:]
