name: Execute dtcw test suite

on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches: [ ng ]
    paths:
      - 'dtcw'
      - 'test/**'
  workflow_dispatch: {}

jobs:
  shellcheck:
    name: ShellCheck - shell script linter
    runs-on: ubuntu-latest
    steps:
      - name: Install used packages
        run: sudo apt-get -qq -y --no-install-recommends install curl ca-certificates ncurses-bin xz-utils
      - uses: actions/checkout@v3
      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: >-
            ./.git/*
            ./test/*
            ./gradlew

  test-dtcw:
    needs: shellcheck
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    name: Execute dtcw test suite - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Clean out dirctory
        # Remove all files except the system under test and the test code.
        run: |
          find . -maxdepth 1 -type d -not -name '.' -not -name 'test' -print0 | xargs -0 rm -rf --
          find . -maxdepth 1 -type f -not -name 'dtcw' -not -name 'test' -print0 | xargs -0 rm --
      - name: Run tests
        run: |
          echo $BASH_VERSION
          test/bats/bin/bats --filter-tags \!e2e test

  test-dtcw-ps1:
    needs: shellcheck
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    name: Execute dtcw test suite - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: pwsh
    steps:
      - name: install pwsh
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            echo "pwsh already installed"
          elif  
            apt-get install -y wget apt-transport-https software-properties-common
            wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
            dpkg -i packages-microsoft-prod.deb
            rm packages-microsoft-prod.deb
            apt-get update
            apt-get install -y powershell
          fi
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      #- name: Clean out dirctory
        # Remove all files except the system under test and the test code.
        # run: |
          # Get-ChildItem -Directory -Path . -Exclude '.', 'test' -Recurse -Force | Remove-Item -Recurse -Force
          # Get-ChildItem -File -Path . -Exclude 'dtcw', 'test' -Force | Remove-Item -Force ``
      - name: remove dtcw (bash)
        run: |
          rm ./dtcw
      - name: Run tests
        run: |
          echo $BASH_VERSION
          test/bats/bin/bats --filter-tags \!e2e test
